#!/usr/bin/env python3
"""Emit the handshake c2p kernel's Dsp_ExecBoot image as a C header for the
ScummVM Atari backend (backends/platform/atari/atari-dsp-c2p.cpp), from the
boot include build.sh generates for HSC2P.TOS, so the backend boots the very
image the test checks."""
import argparse
import hashlib
import re
from pathlib import Path

TASK = Path(__file__).resolve().parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--boot", type=Path, default=TASK / "build/dsp/hsc2p_boot.i")
    parser.add_argument("--output", type=Path,
                        default=TASK.parents[3] / "backends/platform/atari/dsp-c2p-image.h")
    args = parser.parse_args()

    text = args.boot.read_text()
    words = int(re.search(r"HSC2P_BOOT_WORDS\s+equ\s+(\d+)", text).group(1))
    data = [int(value, 16) for value in re.findall(r"\$([0-9a-fA-F]{2})", text.split("hsc2p_boot_image:", 1)[1])]
    if len(data) != words * 3:
        raise SystemExit(f"error: {len(data)} bytes for {words} words")
    source = TASK / "dsp/hsc2p.asm"
    digest = hashlib.sha256(source.read_bytes().replace(b"\r\n", b"\n")).hexdigest()[:16]

    lines = [
        "/* Generated by devtools/atari-falcon030/tools/ssi-dma-c2p/gen-image-header.py",
        f" * from dsp/hsc2p.asm (sha256 {digest}...). Do not edit. */",
        "#ifndef BACKENDS_PLATFORM_ATARI_DSP_C2P_IMAGE_H",
        "#define BACKENDS_PLATFORM_ATARI_DSP_C2P_IMAGE_H",
        "",
        f"/* Dsp_ExecBoot image: the whole kernel, {words} words as bytes. */",
        f"#define ATARI_DSP_C2P_BOOT_WORDS {words}",
        f"static const unsigned char kAtariDspC2pBoot[{len(data)}] = {{",
    ]
    for start in range(0, len(data), 12):
        lines.append("\t" + " ".join(f"0x{value:02x}," for value in data[start:start + 12]))
    lines += ["};", "", "#endif", ""]
    args.output.write_text("\n".join(lines), newline="\n")
    print(f"wrote {args.output} ({words} words)")


if __name__ == "__main__":
    main()
