#!/usr/bin/env python3
"""Emit the DSP kernel's boot and program images as a C header for the
ScummVM Atari backend, from the same LOD files and loader conventions the
Falcon test hosts use (the sibling project's generate_dsp_stage2.py)."""
import argparse
import importlib.util
import sys
from pathlib import Path

from gate_env import source_sha256


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bootstrap", type=Path, required=True)
    parser.add_argument("--program", type=Path, required=True)
    parser.add_argument("--mxdrv-tools", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    spec = importlib.util.spec_from_file_location("stage2", args.mxdrv_tools / "generate_dsp_stage2.py")
    stage2 = importlib.util.module_from_spec(spec)
    sys.modules["stage2"] = stage2          # dataclasses look the module up by name
    spec.loader.exec_module(stage2)
    boot = stage2.make_boot_image(args.bootstrap)
    stream, sections, program_words = stage2.make_program_stream(args.program)
    source = Path(__file__).resolve().parent / "dsp/oplrt.asm"
    digest = source_sha256(source)[:16]

    def rows(values, per_line, fmt):
        out = []
        for i in range(0, len(values), per_line):
            out.append("\t" + ", ".join(fmt % v for v in values[i:i + per_line]) + ",")
        return "\n".join(out)

    boot_bytes = []
    for word in boot:
        boot_bytes += [(word >> 16) & 0xff, (word >> 8) & 0xff, word & 0xff]
    text = (
        "/* Generated by devtools/atari-falcon030/tools/foa-opl3/generate-image-header.py\n"
        " * from dsp/oplrt.asm (sha256 %s...) and the sibling stage-2 loader. Do not edit. */\n"
        "#ifndef BACKENDS_PLATFORM_ATARI_DSP_OPL_IMAGE_H\n#define BACKENDS_PLATFORM_ATARI_DSP_OPL_IMAGE_H\n\n"
        "/* Dsp_ExecBoot image: the two-stage loader, %d words as bytes. */\n"
        "#define ATARI_DSP_OPL_BOOT_WORDS %d\n"
        "static const unsigned char kAtariDspOplBoot[%d] = {\n%s\n};\n\n"
        "/* Stage-two stream: magic, section count, then per section address, length, words;"
        " %d program words in %d sections. */\n"
        "#define ATARI_DSP_OPL_STREAM_WORDS %d\n"
        "#define ATARI_DSP_OPL_STREAM_REPLY_OK 0x%06x\n"
        "static const unsigned long kAtariDspOplStream[%d] = {\n%s\n};\n\n#endif\n"
    ) % (digest, len(boot), len(boot), len(boot_bytes), rows(boot_bytes, 12, "0x%02x"),
         program_words, sections, len(stream), stage2.STAGE2_REPLY_OK, len(stream), rows(stream, 8, "0x%06x"))
    args.output.write_bytes(text.encode())
    print(f"wrote {args.output}: {len(boot)} boot words, {len(stream)} stream words")


if __name__ == "__main__":
    main()
