#!/usr/bin/env python3
"""Generate the OPL log-sine and exponential ROMs for the host and DSP kernels.

Both tables are closed-form, so they are computed rather than copied. The
kernel test checks them against the Nuked ROMs shipped in this tree.

A DSP56001 has 256 words of internal X RAM and 256 of internal Y RAM. These
two 256-entry tables are exactly that size, so the whole waveform ROM lives
on chip: the eight 1,024-entry unpacked waveform tables a desktop build uses
are reconstructed from the quarter sine by index and sign arithmetic instead.
"""
import argparse
import math
from pathlib import Path

LOGSIN = [int(round(-math.log2(math.sin((i + 0.5) * math.pi / 512)) * 256)) for i in range(256)]
EXP = [2 * (int(round((2 ** ((255 - i) / 256.0) - 1) * 1024)) + 1024) for i in range(256)]


def c_table(name, values, per_line=8):
    body = ""
    for start in range(0, len(values), per_line):
        body += "\t" + ", ".join(f"0x{v:04x}" for v in values[start:start + per_line]) + ",\n"
    return f"static const uint16_t {name}[{len(values)}] = {{\n{body}}};\n"


def dsp_table(label, values, per_line=8):
    body = ""
    for start in range(0, len(values), per_line):
        body += "\tdc\t" + ",".join(f"${v:06x}" for v in values[start:start + per_line]) + "\n"
    return f"{label}\n{body}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path, help="C++ header to write")
    parser.add_argument("--dsp", type=Path, help="asm56000 include file to write")
    args = parser.parse_args()
    if args.header:
        args.header.write_text(
            "/* Generated by generate-tables.py. Do not edit. */\n"
            "#ifndef FOA_OPL_TABLES_H\n#define FOA_OPL_TABLES_H\n#include <stdint.h>\n\n"
            "/* Quarter log-sine, 12 bit; -log2(sin((i + 0.5) * pi / 512)) * 256. */\n"
            + c_table("kOplLogSin", LOGSIN) +
            "\n/* Exponential ROM, 12 bit; 2 * ((2^((255 - i) / 256) - 1) * 1024 + 1024). */\n"
            + c_table("kOplExp", EXP) + "\n#endif\n")
    if args.dsp:
        args.dsp.write_text(
            "; Generated by generate-tables.py. Do not edit.\n"
            "; Quarter log-sine (X) and exponential ROM (Y), 256 words each.\n"
            + dsp_table("oplLogSin", LOGSIN) + "\n" + dsp_table("oplExp", EXP))
    if not args.header and not args.dsp:
        print(f"logsin {min(LOGSIN)}..{max(LOGSIN)}  exp {min(EXP)}..{max(EXP)}")


if __name__ == "__main__":
    main()
